.TH tdk 3 ${VERSION}

.SH NAME

.PP
tdk - Terminal Development Kit

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBint\fR tdk_getcpos(\fBint\fR \fI*col\fR, \fBint\fR \fI*ln\fR);
\fBint\fR tdk_getkey(\fBvoid\fR);
\fBint\fR tdk_getwdim(\fBint\fR \fI*col\fR, \fBint\fR \fI*ln\fR);
\fBint\fR tdk_setcpos(\fBint\fR \fIcol\fR, \fBint\fR \fIln\fR);
\fBvoid\fR tdk_beep(\fBvoid\fR);
\fBvoid\fR tdk_clearln(\fBvoid\fR);
\fBvoid\fR tdk_setclr(\fBint\fR \fIclr\fR, \fBint\fR \fIlyr\fR);
\fBvoid\fR tdk_setcshp(\fBint\fR \fIshp\fR);
\fBvoid\fR tdk_setcvis(\fBint\fR \fIisvis\fR);
\fBvoid\fR tdk_seteff(\fBint\fR \fIeff\fR, \fBint\fR \fIisenb\fR);
\fBvoid\fR tdk_setlum(\fBint\fR \fIlum\fR);
\fBvoid\fR tdk_setwalt(\fBint\fR \fIisenb\fR);
.fi

.SH STANDARDS

.PP
C99, POSIX.1-2008

.SH DESCRIPTION

.PP
A simple C99 terminal manipulation library for Linux that is capable of handling some terminal properties, styles and key readings with UTF-8 encoding.

.PP
In order to be kept small, it lacks proper parameter validation and resets. It
trust in its user to follow these rules:

.IP \\[bu]
The terminal properties can not be handled manually: including the use of
other manipulation functions or output of ANSI escape sequences.

.IP \\[bu]
The stdin stream must be kept oriented to wide-characters, while the stdout
and stderr streams, to single-byte characters.

.IP \\[bu]
All of its functions must be used as stated in their man pages.

.PP
For further details about its functions, check out their respective man pages.

.SH THREAD-SAFETY

.PP
Operations involving I/O are, by nature, non thread-safe, thus functions in this
library neither.

.SH RESERVED NAMES

.PP
This library reserves names starting with "tdk_" and "TDK_", possibly prefixed
by an underline to indicate implementation restrictions.

.SH INCLUDED HEADERS

.PP
When included, it will automatically include its dependency headers:

.nf
\fB#include\fR <fcntl.h>
\fB#include\fR <locale.h>
\fB#include\fR <stdarg.h>
\fB#include\fR <stdio.h>
\fB#include\fR <stdlib.h>
\fB#include\fR <sys/ioctl.h>
\fB#include\fR <termios.h>
\fB#include\fR <unistd.h>
\fB#include\fR <wchar.h>
.fi

.SH SOURCE CODE

.PP
Its source code is available at <https://github.com/skippyr/libtdk>.

.SH HELP

.PP
If you need help about this project, open a new issue in its issues page
(<https://github.com/skippyr/libtdk/issues>) or send me an e-mail
(<mailto:skippyr.developer@gmail.com>) describing what is going on.

.SH CONTRIBUTING

.PP
This project is open to review and possibly accept contributions, specially
fixes and suggestions. If you are interested, send your contribution to its
pull requests page (<https://github.com/skippyr/libtdk/pulls>) or to my
e-mail (<mailto:skippyr.developer@gmail.com>).

.PP
By contributing to this project, you must agree to license your work under the
same license that the project uses.

.SH LICENSE

.PP
This project is licensed under the BSD-3-Clause License. Refer to the LICENSE
file that comes in its source code for license and copyright details.
