.TH tdk_ringBell 3 ${VERSION}

.SH NAME

.PP
tdk_ringBell - rings the terminal bell

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

void tdk_ringBell(void);\fR
.fi

.SH DESCRIPTION

.PP
Rings the terminal bell, possibly emitting a bell indicator in the title bar, window flash, system notification sound or a beep from the motherboard speaker.

.SH EXAMPLES

.nf
#include <tdk.h>

int main(void) {
  tdk_ringBell();
  return 0;
}
.fi

.SH NOTES

.TP
.IP \\[bu]
Some terminals have the bell feature disabled by default.

.TP
.IP \\[bu]
This function caches ANSI escape sequences in the standard output buffer if the standard output stream is a TTY.

Before writting to the standard error stream, ensure to flush the standard output buffer by using \fBfflush\fR(3) for them to be used.

.TP
.IP \\[bu]
The terminal bell is not ring if the standard output and error streams are being redirected/piped or are wide character oriented.

.SH SEE ALSO

.BR fflush (3),
.BR tdk (3)
