.TH tdk_getWindowDimensions 3 ${VERSION}

.SH NAME

.PP
tdk_getWindowDimensions - gets the terminal window dimensions

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

int tdk_getWindowDimensions(unsigned short *\fItotalColumns\fB,
                            unsigned short *\fItotalRows\fB);\fR
.fi

.SH DESCRIPTION

.PP
Gets the total of columns and rows in terminal window and puts that information into the addresses pointed by the \fItotalColumns\fR and \fItotalRows\fR parameters, respectively, if successful.

.PP
Both parameters are optional. If one is not required, use NULL.

.SH RETURN VALUES

.PP
It returns 0 on success, and -1 on failure. It fails if:

.TP
.IP \\[bu]
All standard streams are being redirected/piped.

.SH EXAMPLES

.nf
#include <stdio.h>

#include <tdk.h>

int main(void) {
  unsigned short totalColumnsInWindow;
  unsigned short totalRowsInWindow;
  tdk_getWindowDimensions(&totalColumnsInWindow, &totalRowsInWindow);
  printf("Total columns: %hu.\\n", totalColumnsInWindow);
  printf("Total rows   : %hu.\\n", totalRowsInWindow);
  return 0;
}
.fi

.SH SEE ALSO

.BR printf (3),
.BR tdk (3)
