.TH tdk_setCursorPosition 3 "${LIBRARY_VERSION}" "${LIBRARY_PACKAGE}"

.SH NAME

.PP
tdk_setCursorPosition - it sets the terminal cursor position.

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.PP
\fBint\fR tdk_setCursorPosition(\fBint\fR \fIcolumn\fR, \fBint\fR \fIline\fR);

.SH DESCRIPTION

.PP
It sets the terminal cursor column and line positions to be \fIcolumn\fR and
\fIline\fR respectively.

It considers an origin position, where position is (column = 0, line = 0), at
the top left corner of the screen, increasing those values going right and down
respectively.

.SH RETURN VALUES

.PP
It returns 0 if the position was set successfully, and 1 otherwise. It fails if:

.IP \\[bu]
The stdout and stderr streams are being redirected or are not oriented to
single-byte characters.

.IP \\[bu]
The position given through its parameters is outside of the screen boundaries.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR) {
  /* It sets the cursor position at the top left corner of the screen. */
  tdk_setCursorPosition(0, 0);
  /* It writes a cool message. */
  printf("Here Are Dragons!\\n");
  return 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
