.TH tdk_clearCursorLine 3 ${VERSION}

.SH NAME

.PP
tdk_clearCursorLine - clears the terminal cursor line

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

void tdk_clearCursorLine(void);\fR
.fi

.SH DESCRIPTION

.PP
Clears the terminal cursor line and puts the cursor at its beginning, allowing its contents to be repainted.

.SH EXAMPLES

.nf
#include <stdio.h>

#include <tdk.h>

int main(void)
{
    printf("Hello, world!");
    tdk_clearCursorLine();
    puts("Here Be Dragons!");
    return 0;
}
.fi

.SH NOTES

.TP
.IP \\[bu]
This function caches ANSI escape sequences in the standard output buffer if the standard output stream is a TTY.

Before writting to the standard error stream, ensure to flush the standard output buffer by using \fBfflush\fR(3) for them to be used.

.TP
.IP \\[bu]
It will not clear the line if the standard output and error streams are being redirected/piped or are wide character oriented.

.SH SEE ALSO

.BR fflush (3),
.BR printf (3),
.BR puts (3),
.BR tdk (3)
