.TH tdk_clearin 3 ${VERSION}

.SH NAME

.PP
tdk_clearin - it clears the terminal input buffer

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_clearin(\fBvoid\fR);
.fi

.SH DESCRIPTION

.PP
It removes all the characters present in the terminal input buffer, allowing you to perform readings once again without the risk of reading an unintended character from that buffer.

.SH EXAMPLES

.nf
\fB#include\fR <stddef.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBint\fR key;
	tdk_clearin();
	tdk_readkey(&key, NULL);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
