.TH tdk_clearInputBuffer 3 ${VERSION}

.SH NAME

.PP
tdk_clearInputBuffer - clears the standard input buffer

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

void tdk_clearInputBuffer(void);\fR
.fi

.SH DESCRIPTION

.PP
It clears the standard input buffer, allowing new readings to be performed without conflicts with existing contents.

.SH EXAMPLES

.nf
#include <tdk.h>

int main(void)
{
    struct tdk_KeyEvent keyEvent;
    tdk_clearInputBuffer();
    tdk_readKeyEvent(&keyEvent);
    return 0;
}
.fi

.SH NOTES

.TP
.IP \\[bu]
It will not clear the standard input buffer if the standard input stream is being redirected/piped or is wide character oriented.

.SH SEE ALSO

.BR tdk (3)
