.TH tdk_setcpos 3 ${VERSION}

.SH NAME

.PP
tdk_setcpos - it sets the terminal cursor position

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_setcpos(\fBunsigned short int\fR \fIcol\fR, \fBunsigned short int\fR \fIrow\fR);
.fi

.SH DESCRIPTION

.PP
It sets the terminal cursor column and row positions to be \fIcol\fR and \fIrow\fR, respectively.

.PP
It considers an origin position at the top left corner of the screen, where (col = 0, row = 0). The column and row positions increase going right and down, respectively.

.PP
For a much fine control, combine it with tdk_getwdim() (3) and tdk_getcpos() (3).

.PP
The position will not be applied if it is outside of the terminal window boundaries or if the standard output and error streams are being redirected.

.SH EXAMPLES

.nf
\fB#include\fR <stdio.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBunsigned short int\fR crow;
	tdk_getcpos(NULL, &crow);
	tdk_setcpos(5, crow);
	printf("Here Are Dragons!\fB\\n\fR");
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3),
.BR tdk_getwdim (3),
.BR tdk_getcpos (3)
