.TH tdk_seteff 3 ${VERSION}

.SH NAME

.PP
tdk_seteff - it enables/disables terminal text effects

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_seteff(\fBint\fR \fIeff\fR, \fBint\fR \fIisenb\fR);
.fi

.SH DESCRIPTION

.PP
It enables/disables the terminal text effects flagged in the bitmask \fIeff\fR based on the value of the boolean \fIisenb\fR.

.PP
Any custom effects applied must be manually reset before the end of your program to avoid messing up the shell session of the user.

.PP
No effect will be applied if the standard output and error streams are being redirected.

.SH EFFECTS

.PP
These are the bitmask flags defined by the library to identify effects. They may be used to compose the bitmask of the \fIeff\fR parameter:

.TP
.B TDK_EFFITL
The italic effect: it makes the text curly. It may require the use of a font with italic style.

.TP
.B TDK_EFFUND
The underline effect: it draws a horizontal line below the text.

.TP
.B TDK_EFFBLK
The blinking effect: it makes the text blink indefinetely over time.

.TP
.B TDK_EFFREV
The reverse-video effect: it swaps the foreground and background colors.

.TP
.B TDK_EFFCON
The conceal effect: it makes the text hard to read or invisible.

.TP
.B TDK_EFFSTR
The strike-through effect: it draws a horizontal line crossing through the middle of the text.

.PP
Terminals may implement certain effects differently or not at all.

.SH EXAMPLES

.nf
\fB#include\fR <stdio.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBchar\fR msg[] = "Here Are Dragons!";
	tdk_seteff(TDK_EFFREV | TDK_EFFUND, 1);
	printf("%s\fB\\n\fR", msg);
	tdk_seteff(TDK_EFFREV, 0);
	printf("%s\fB\\n\fR", msg);
	tdk_seteff(TDK_EFFUND, 0);
	printf("%s\fB\\n\fR", msg);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
