.TH tdk_setcvis 3 ${VERSION}

.SH NAME

.PP
tdk_setcvis - it sets the terminal cursor visibility

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_setcvis(\fBint\fR \fIisvis\fR);
.fi

.SH DESCRIPTION

.PP
It sets the terminal cursor visibility based on value of the boolean \fIisvis\fR.

.PP
The visibility must be manually reset before the end of your program to avoid messing up the shell session of the user.

.PP
The visibility will not be set if the standard output and error streams are being redirected.

.SH EXAMPLES

.nf
\fB#include\fR <stddef.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBint\fR key;
	tdk_setcvis(0);
	tdk_readkey(&key, NULL);
	tdk_setcvis(1);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
