.TH tdk_setwalt 3 ${VERSION}

.SH NAME

.PP
tdk_setwalt - it opens/closes the terminal alternate screen

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_setwalt(\fBint\fR \fIisenb\fR);
.fi

.SH DESCRIPTION

.PP
It opens/closes the terminal alternate screen based on the value of the boolean \fIisenb\fR.

.PP
The alternate screen is an alternative screen buffer that can be used instead of the primary one. This allow you to reset back to the original one once your program is done, making it look like it ran separately.

.PP
If the terminal you are using do not have the alternate screen feature, all changes will get applied to the primary screen buffer instead.

.PP
After opened, the alternate screen must be manually closed before the end of your program to avoid messing up the shell session of the user. Opening the alternate screen while it is already opened, clears it.

.SH EXAMPLES

.nf
\fB#include\fR <stdio.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBint\fR key;
	tdk_setwalt(1);
	printf("Here Are Dragons!\\n");
	tdk_readkey(&key, NULL);
	tdk_setwalt(0);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
