.TH tdk_setwalt 3 MANDATE tdk
.SH NAME
.PP
tdk_setwalt - it enables/disables the alternate screen

.SH LIBRARY
.PP
tdk (libtdk, -ltdk)

.SH SYNOPSIS
.PP
#include <tdk.h>

.PP
void tdk_setwalt(int isenb);

.SH DESCRIPTION
.PP
It enables/disables the alternate screen based on the boolean isenb. Enabling
the alternate screen while it is enabled resets it.

.SH EXAMPLES
.PP
tdk_setwalt(1);

.SH SEE ALSO
.BR tdk (3)
