.TH tdk_getwindim 3 ${VERSION}

.SH NAME

.PP
tdk_getwindim - gets the terminal window dimensions

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

int tdk_getwindim(unsigned short *\fIcols\fB, unsigned short *\fIrows\fB);\fR
.fi

.SH DESCRIPTION

.PP
It gets the terminal window dimensions and sets the total of columns and rows into the addressed pointed by the \fIcols\fR and \fIrows\fR parameters, respectively, if successful.

.SH RETURN VALUES

.PP
It returns 0 on success, and -1 on failure. It fails if:

.TP
.IP \\[bu]
All standard streams are being redirected/piped.

.SH EXAMPLES

.nf
#include <stdio.h>

#include <tdk.h>

int
main(void)
{
    unsigned short cols;
    unsigned short rows;
    tdk_getwindim(&cols, &rows);
    printf("cols: %hu.\\n", cols);
    printf("rows: %hu.\\n", rows);
    return 0;
}
.fi

.SH SEE ALSO

.BR printf (3),
.BR tdk (3)
