.TH tdk_clearln 3 ${VERSION}

.SH NAME

.PP
tdk_clearln - it clears the terminal cursor line

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_clearln(\fBvoid\fR);
.fi

.SH DESCRIPTION

.PP
It removes all the characters in the terminal cursor line and puts the cursor at its beginning.

.PP
It is usually used to redraw parts of the user interface.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR
main(\fBvoid\fR)
{
	printf("Hello, world!");
	tdk_clearln();
	printf("Here Are Dragons!\\n");
	\fBreturn\fR 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
