.TH tdk_setaltwin 3 ${VERSION}

.SH NAME

.PP
tdk_setaltwin - sets the state of the alternate window buffer

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-tdk\fR)

.SH SYNOPSIS

.nf
\fB#include <tdk.h>

void tdk_setaltwin(int \fIisenb\fB);\fR
.fi

.SH DESCRIPTION

.PP
It sets the state of the alternate window buffer based on the value of the boolean \fIisenb\fR: a non-zero value enables it, while zero disables it.

.SH EXAMPLES

.nf
#include <tdk.h>

int
main(void)
{
    tdk_setaltwin(1);
    printf("Here Be Dragons!");
    tdk_readkey(NULL, NULL);
    tdk_setaltwin(0);
    return 0;
}
.fi

.SH NOTES

.TP
.IP \\[bu]
If enabled, the state of the alternate window buffer must be reset before the end of your program to avoid conflicts with the current shell session.

.TP
.IP \\[bu]
The state of the alternate window buffer is not set if the standard output and error streams are being redirected/piped or are wide character oriented.

.TP
.IP \\[bu]
This function caches ANSI escape sequences in the standard output buffer if the standard output stream is a TTY.

Before writting to the standard error stream, ensure to flush the standard output buffer by using \fBfflush\fR(3) for them to be used.

.SH SEE ALSO

.BR fflush (3),
.BR printf (3),
.BR tdk (3)
.BR tdk_readkey (3)
