.TH tdk_getwdim 3 ${VERSION}

.SH NAME

.PP
tdk_getwdim - it gets the terminal window dimensions

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBint\fR tdk_getwdim(\fBint\fR \fI*col\fR, \fBint\fR \fI*ln\fR);
.fi

.SH DESCRIPTION

.PP
It gets the total of columns and lines in the terminal window and puts those
values inside of the addresses pointed by \fIcol\fR and \fIln\fR, respectively.

.SH RETURN VALUES

.PP
It returns 0 on success, and 1 on failure.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR) {
  \fBint\fR wcol;
  \fBint\fR wln;
  tdk_getwdim(&wcol, &wln);
  printf(":: Window Dimensions (columns = %d, lines = %d).\\n", wcol, wln);
  \fBreturn\fR 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
