.TH tdk_getcpos 3 ${VERSION} ${PKG}

.SH NAME

.PP
tdk_getcpos - it gets the terminal cursor position

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBint\fR tdk_getcpos(\fBint\fR \fI*col\fR, \fBint\fR \fI*ln\fR);
.fi

.SH DESCRIPTION

.PP
It gets the terminal cursor column and line positions and put those values
inside of the addresses pointed by \fIcol\fR and \fIln\fR, respectively.

.PP
It considers an origin position at the top left corner of the terminal window.
The column and line positions increase going right and down, respectively.

.PP
If a position is not required, its address may be set to NULL.

.PP
Upon success, it clears the stdin buffer.

.SH RETURN VALUES

.PP
It returns 0 on success, and 1 on failure.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR
main(\fBvoid\fR)
{
	\fBint\fR ccol;
	\fBint\fR cln;
	tdk_getcpos(&ccol, &cln);
	printf(":: Cursor Position (column = %d, line = %d).\\n", ccol, cln);
	\fBreturn\fR 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
