.TH tdk_beep 3 ${VERSION} ${PACKAGE}

.SH NAME

.PP
tdk_beep - it rings the terminal bell

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_beep(\fBvoid\fR);
.fi

.SH DESCRIPTION

.PP
It rings the terminal bell, possibly emitting a system notification sound or
a beep from the motherboard speaker.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR
main(\fBvoid\fR)
{
	tdk_beep();
	\fBreturn\fR 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
