.TH tdk_setlum 3 ${VERSION}

.SH NAME

.PP
tdk_setlum - it sets the terminal text luminosity

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_setlum(\fBint\fR \fIlum\fR);
.fi

.SH DESCRIPTION

.PP
It sets the terminal text luminosity \fIlum\fR.

.PP
Any custom luminosity applied must be manually reset before the end of your program to avoid messing up the shell session of the user.

.PP
No luminosity will be applied if the standard output and error streams are being redirected.

.SH LUMINOSITY

.PP
These are values defined by the library to identify luminosity levels:

.TP
.B TDK_LUMDFT
The default luminosity. Used for resets.

.TP
.B TDK_LUMBLD
The bold luminosity: usually rendered with bold weight and or with light colors. It may require the use of a font with bold weight.

.TP
.B TDK_LUMDIM
The dim luminosity: usually rendered with faint colors.

.PP
Terminals may implement certain luminosity levels differently or not at all.

.SH EXAMPLES

.nf
\fB#include\fR <stdio.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBchar\fR msg[] = "Here Are Dragons!";
	tdk_setlum(TDK_LUMBLD);
	printf("%s\fB\\n\fR", msg);
	tdk_setlum(TDK_LUMDIM);
	printf("%s\fB\\n\fR", msg);
	tdk_setlum(TDK_LUMDFT);
	printf("%s\fB\\n\fR", msg);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
