.TH tdk_setclr 3 MANDATE tdk
.SH NAME
.PP
tdk_setclr - it sets a terminal color

.SH LIBRARY
.PP
tdk (libtdk, -ltdk)

.SH SYNOPSIS
.PP
#include <tdk.h>

.PP
void tdk_setclr(int lyr, int clr);

.SH DESCRIPTION
.PP
It sets the color clr in the layer specified as lyr.

.SH LAYERS
.PP
The lyr parameter can be:

.TP
.B tdk_LyrFg
The foreground layer.

.TP
.B tdk_LyrBg
The background layer.

.SH COLORS
.PP
The clr parameter can be:

.TP
.B tdk_ClrDft
The default color.
.TP
.B tdk_ClrBlk
The black color.
.TP
.B tdk_ClrRed
The red color.
.TP
.B tdk_ClrGrn
The green color.
.TP
.B tdk_ClrYlw
The yellow color.
.TP
.B tdk_ClrBle
The blue color.
.TP
.B tdk_ClrMag
The magenta color.
.TP
.B tdk_ClrCyn
The cyan color.
.TP
.B tdk_ClrWht
The white color.

.SH EXAMPLES
.PP
tdk_setclr(tdk_LyrFg, tdk_ClrRed);

.SH NOTES
.IP \[bu]
Terminals usually have issues rendering the line-feed character (\\n) with a
background color.

.IP \[bu]
Some terminal themes have black and white colors not corresponding to their
background and foreground colors, which can make text unreadable if those
colors are swapped using this function.

.SH SEE ALSO
.BR tdk (3)
