.TH tdk_setCursorVisibility 3 "${LIBRARY_VERSION}" "${LIBRARY_PACKAGE}"

.SH NAME

.PP
tdk_setCursorVisibility - it hides/show the terminal cursor.

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.PP
\fBvoid\fR tdk_setCursorVisibility(\fBint\fR \fIisToMakeVisible\fR);

.SH DESCRIPTION

It hides/shows the terminal cursor based on the boolean \fIisToMakeVisible\fR.
It will not do a thing if the stdout and stderr streams are being redirected or
are not oriented to single-byte characters.

.SH EXAMPLES

.nf
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR) {
  /* It makes the cursor invisible. */
  tdk_setCursorVisibility(0);
  /* It waits for a key. */
  tdk_readKey();
  /* It makes the cursor visible. */
  tdk_setCursorVisibility(1);
  return 0;
}
.fi

.SH SEE ALSO

.BR tdk (3)
