.TH tdk_setlum 3 MANDATE tdk
.SH NAME
.PP
tdk_setlum - it sets the foreground color luminosity

.SH LIBRARY
.PP
tdk (libtdk, -ltdk)

.SH SYNOPSIS
.PP
#include <tdk.h>

.PP
void tdk_setlum(int lum);

.SH DESCRIPTION
.PP
It sets the foreground color luminosity lum.

.SH LUMINOSITY
The lum parameter can be:

.TP
.B tdk_LumDft
The default luminosity.

.TP
.B tdk_LumBld
The bold luminosity: usually rendered as bold and/or with light colors.

.TP
.B tdk_LumDim
The dim luminosity: usually rendered with faint colors.

.SH EXAMPLES
.PP
tdk_setlum(tdk_LumBld);

.SH NOTES
.PP
Terminals may render luminosity differently or not support them.

.SH SEE ALSO
.BR tdk (3)
