.TH tdk_setcshp 3 ${VERSION}

.SH NAME

.PP
tdk_setcshp - it sets the terminal cursor shape

.SH LIBRARY

.PP
tdk (\fIlibtdk\fR, \fI-ltdk\fR)

.SH SYNOPSIS

.nf
\fB#include\fR <tdk.h>

\fBvoid\fR tdk_setcshp(\fBint\fR \fIshp\fR);
.fi

.SH DESCRIPTION

.PP
It sets the terminal cursor shape \fIshp\fR.

.PP
A custom shape must be manually reset before the end of your program to avoid messing up the shell session of the user.

.PP
No shape will be applied if the standard output and error streams are being redirected.

.SH SHAPES

.PP
There are values defined by the library to identify shapes:

.TP
.B TDK_SHPDFT
The default shape. Used for resets.

.TP
.B TDK_SHPBLK, TDK_SHPBBLK
The block shape.

.TP
.B TDK_SHPUND, TDK_SHPBUND
The underline shape.

.TP
.B TDK_SHPBAR, TDK_SHPBBAR
The bar shape.

.PP
Shapes prefixed with B are blinking variants of that same shape. However, some terminal do not render blinking cursors by default.

.SH EXAMPLES

.nf
\fB#include\fR <stddef.h>
\fB#include\fR <tdk.h>

\fBint\fR main(\fBvoid\fR)
{
	\fBint\fR key;
	tdk_setcshp(TDK_SHPUND);
	tdk_readkey(&key, NULL);
	tdk_setcshp(TDK_SHPDFT);
	\fBreturn\fR (0);
}
.fi

.SH SEE ALSO

.BR tdk (3)
