LIBRARY_VERSION:=v5.0.0
LIBRARY_PACKAGE:=Mistureba
COMPILER:=cc
COMPILER_OPTIONS:=-std=c99 -pedantic -Os -Wall
SHELL:=/bin/sh
INSTALLATION_BASE_PATH:=/usr/local
INSTALLATION_MAN3_PATH:=${INSTALLATION_BASE_PATH}/man/man3
INSTALLATION_INCLUDE_PATH:=${INSTALLATION_BASE_PATH}/include
INSTALLATION_LIBRARY_PATH:=${INSTALLATION_BASE_PATH}/lib
